version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout

      - run: cd cmd/provisionize && go build
      - run: cd cmd/provisionizer && go build
      - run: cd cmd/deprovisionizer && go build
