version: 2
jobs:
  build_provisionize:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: cd cmd/provisionize && go build
      
  build_provisionizer:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: cd cmd/provisionizer && go build
      
  build_deprovisionize:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: cd cmd/deprovisionizer && go build
      
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go test -v -cover -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_provisionize
      - build_provisionizer
      - build_deprovisionize
      - test
