// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provisionize.proto

package provisionize

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type VirtualMachine struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClusterName          string   `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	TemplateName         string   `protobuf:"bytes,4,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	MemoryMb             uint32   `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuCores             uint32   `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	Ipv4Addresses        []string `protobuf:"bytes,7,rep,name=ipv4_addresses,json=ipv4Addresses,proto3" json:"ipv4_addresses,omitempty"`
	Ipv6Addresses        []string `protobuf:"bytes,8,rep,name=ipv6_addresses,json=ipv6Addresses,proto3" json:"ipv6_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualMachine) Reset()         { *m = VirtualMachine{} }
func (m *VirtualMachine) String() string { return proto.CompactTextString(m) }
func (*VirtualMachine) ProtoMessage()    {}
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{1}
}

func (m *VirtualMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachine.Unmarshal(m, b)
}
func (m *VirtualMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachine.Marshal(b, m, deterministic)
}
func (m *VirtualMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachine.Merge(m, src)
}
func (m *VirtualMachine) XXX_Size() int {
	return xxx_messageInfo_VirtualMachine.Size(m)
}
func (m *VirtualMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachine.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachine proto.InternalMessageInfo

func (m *VirtualMachine) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VirtualMachine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualMachine) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *VirtualMachine) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *VirtualMachine) GetMemoryMb() uint32 {
	if m != nil {
		return m.MemoryMb
	}
	return 0
}

func (m *VirtualMachine) GetCpuCores() uint32 {
	if m != nil {
		return m.CpuCores
	}
	return 0
}

func (m *VirtualMachine) GetIpv4Addresses() []string {
	if m != nil {
		return m.Ipv4Addresses
	}
	return nil
}

func (m *VirtualMachine) GetIpv6Addresses() []string {
	if m != nil {
		return m.Ipv6Addresses
	}
	return nil
}

type ProvisionVirtualMachineRequest struct {
	RequestId            string          `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	VirtualMachine       *VirtualMachine `protobuf:"bytes,2,opt,name=virtual_machine,json=virtualMachine,proto3" json:"virtual_machine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProvisionVirtualMachineRequest) Reset()         { *m = ProvisionVirtualMachineRequest{} }
func (m *ProvisionVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionVirtualMachineRequest) ProtoMessage()    {}
func (*ProvisionVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{2}
}

func (m *ProvisionVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionVirtualMachineRequest.Unmarshal(m, b)
}
func (m *ProvisionVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionVirtualMachineRequest.Merge(m, src)
}
func (m *ProvisionVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionVirtualMachineRequest.Size(m)
}
func (m *ProvisionVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionVirtualMachineRequest proto.InternalMessageInfo

func (m *ProvisionVirtualMachineRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ProvisionVirtualMachineRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*VirtualMachine)(nil), "VirtualMachine")
	proto.RegisterType((*ProvisionVirtualMachineRequest)(nil), "ProvisionVirtualMachineRequest")
}

func init() { proto.RegisterFile("provisionize.proto", fileDescriptor_551987ef9813264c) }

var fileDescriptor_551987ef9813264c = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x5d, 0x37, 0xb7, 0xf5, 0xdd, 0xd6, 0x41, 0xbc, 0x14, 0x45, 0x9d, 0x15, 0x61, 0xa7,
	0x1e, 0xa6, 0x0c, 0xf1, 0x26, 0x9e, 0x3c, 0x4c, 0x66, 0x05, 0xaf, 0xa5, 0x4b, 0x5f, 0x34, 0xd0,
	0x2c, 0x35, 0x7f, 0x0a, 0xf3, 0xec, 0x07, 0x97, 0x26, 0xeb, 0xd8, 0x3c, 0x78, 0x7b, 0xdf, 0xe7,
	0xf9, 0x3d, 0x21, 0x3c, 0x09, 0x90, 0x52, 0x8a, 0x8a, 0x29, 0x26, 0xd6, 0xec, 0x1b, 0xe3, 0x52,
	0x0a, 0x2d, 0xa2, 0x39, 0x74, 0x13, 0x54, 0xa6, 0xd0, 0x84, 0x40, 0x87, 0x8a, 0x1c, 0xc3, 0xd6,
	0xa4, 0x35, 0x1d, 0x25, 0x76, 0x26, 0x21, 0xf4, 0x38, 0x2a, 0x95, 0x7d, 0x60, 0xe8, 0x4d, 0x5a,
	0x53, 0x3f, 0x69, 0xd6, 0xe8, 0xc7, 0x83, 0xe0, 0x9d, 0x49, 0x6d, 0xb2, 0x62, 0x91, 0xd1, 0x4f,
	0xb6, 0x46, 0x12, 0x80, 0xc7, 0x72, 0x1b, 0xf7, 0x13, 0x8f, 0xe5, 0xf5, 0x81, 0xeb, 0x8c, 0x37,
	0x49, 0x3b, 0x93, 0x2b, 0x18, 0xd2, 0xc2, 0x28, 0x8d, 0x32, 0xb5, 0x5e, 0xdb, 0x7a, 0x83, 0xad,
	0xf6, 0x52, 0x23, 0xd7, 0x30, 0xd2, 0xc8, 0xcb, 0x22, 0xd3, 0xe8, 0x98, 0x8e, 0x65, 0x86, 0x8d,
	0x68, 0xa1, 0x33, 0xf0, 0x39, 0x72, 0x21, 0x37, 0x29, 0x5f, 0x85, 0xc7, 0xf6, 0xc6, 0x7d, 0x27,
	0x2c, 0x56, 0xb5, 0x49, 0x4b, 0x93, 0x52, 0x21, 0x51, 0x85, 0x5d, 0x67, 0xd2, 0xd2, 0x3c, 0xd5,
	0x3b, 0xb9, 0x81, 0x80, 0x95, 0xd5, 0x5d, 0x9a, 0xe5, 0xb9, 0x44, 0xa5, 0x50, 0x85, 0xbd, 0x49,
	0x7b, 0xea, 0x27, 0xa3, 0x5a, 0x7d, 0x6c, 0xc4, 0x2d, 0x36, 0xdf, 0xc3, 0xfa, 0x3b, 0x6c, 0xbe,
	0xc3, 0xa2, 0x0d, 0x5c, 0x2c, 0x9b, 0x52, 0x0f, 0xeb, 0x48, 0xf0, 0xcb, 0xa0, 0xd2, 0xe4, 0x1c,
	0x40, 0xba, 0x31, 0xdd, 0xb5, 0xe3, 0x6f, 0x95, 0xe7, 0x9c, 0xdc, 0xc3, 0xb8, 0x72, 0xb9, 0x94,
	0xbb, 0xa0, 0xed, 0x6b, 0x30, 0x1b, 0xc7, 0x7f, 0xce, 0x0b, 0xaa, 0x83, 0x7d, 0xf6, 0x0a, 0x27,
	0xcb, 0xbd, 0xf7, 0x7c, 0x43, 0x59, 0x31, 0x8a, 0xe4, 0x01, 0x86, 0xfb, 0x32, 0xb9, 0x8c, 0xff,
	0xbf, 0xe0, 0x69, 0x2f, 0x76, 0x1f, 0x20, 0x3a, 0x5a, 0x75, 0xed, 0x9f, 0xb8, 0xfd, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x59, 0x0f, 0xd6, 0x9d, 0x29, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProvisionizeServiceClient is the client API for ProvisionizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProvisionizeServiceClient interface {
	Provisionize(ctx context.Context, in *ProvisionVirtualMachineRequest, opts ...grpc.CallOption) (*Result, error)
}

type provisionizeServiceClient struct {
	cc *grpc.ClientConn
}

func NewProvisionizeServiceClient(cc *grpc.ClientConn) ProvisionizeServiceClient {
	return &provisionizeServiceClient{cc}
}

func (c *provisionizeServiceClient) Provisionize(ctx context.Context, in *ProvisionVirtualMachineRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/ProvisionizeService/Provisionize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionizeServiceServer is the server API for ProvisionizeService service.
type ProvisionizeServiceServer interface {
	Provisionize(context.Context, *ProvisionVirtualMachineRequest) (*Result, error)
}

func RegisterProvisionizeServiceServer(s *grpc.Server, srv ProvisionizeServiceServer) {
	s.RegisterService(&_ProvisionizeService_serviceDesc, srv)
}

func _ProvisionizeService_Provisionize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionizeServiceServer).Provisionize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProvisionizeService/Provisionize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionizeServiceServer).Provisionize(ctx, req.(*ProvisionVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProvisionizeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ProvisionizeService",
	HandlerType: (*ProvisionizeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Provisionize",
			Handler:    _ProvisionizeService_Provisionize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provisionize.proto",
}
