// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provisionize.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	Success              bool             `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ServiceResults       []*ServiceResult `protobuf:"bytes,2,rep,name=serviceResults,proto3" json:"serviceResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Result) GetServiceResults() []*ServiceResult {
	if m != nil {
		return m.ServiceResults
	}
	return nil
}

type ServiceResult struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage         string   `protobuf:"bytes,4,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceResult) Reset()         { *m = ServiceResult{} }
func (m *ServiceResult) String() string { return proto.CompactTextString(m) }
func (*ServiceResult) ProtoMessage()    {}
func (*ServiceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{1}
}

func (m *ServiceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceResult.Unmarshal(m, b)
}
func (m *ServiceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceResult.Marshal(b, m, deterministic)
}
func (m *ServiceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceResult.Merge(m, src)
}
func (m *ServiceResult) XXX_Size() int {
	return xxx_messageInfo_ServiceResult.Size(m)
}
func (m *ServiceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceResult.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceResult proto.InternalMessageInfo

func (m *ServiceResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ServiceResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ServiceResult) GetDebugMessage() string {
	if m != nil {
		return m.DebugMessage
	}
	return ""
}

type IPConfig struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength         uint32   `protobuf:"varint,2,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	Gateway              string   `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPConfig) Reset()         { *m = IPConfig{} }
func (m *IPConfig) String() string { return proto.CompactTextString(m) }
func (*IPConfig) ProtoMessage()    {}
func (*IPConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{2}
}

func (m *IPConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPConfig.Unmarshal(m, b)
}
func (m *IPConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPConfig.Marshal(b, m, deterministic)
}
func (m *IPConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPConfig.Merge(m, src)
}
func (m *IPConfig) XXX_Size() int {
	return xxx_messageInfo_IPConfig.Size(m)
}
func (m *IPConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IPConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IPConfig proto.InternalMessageInfo

func (m *IPConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *IPConfig) GetPrefixLength() uint32 {
	if m != nil {
		return m.PrefixLength
	}
	return 0
}

func (m *IPConfig) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

type VirtualMachine struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fqdn                 string    `protobuf:"bytes,3,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	ClusterName          string    `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	TemplateName         string    `protobuf:"bytes,5,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	MemoryMb             uint32    `protobuf:"varint,6,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuCores             uint32    `protobuf:"varint,7,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	Ipv4                 *IPConfig `protobuf:"bytes,8,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6                 *IPConfig `protobuf:"bytes,9,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VirtualMachine) Reset()         { *m = VirtualMachine{} }
func (m *VirtualMachine) String() string { return proto.CompactTextString(m) }
func (*VirtualMachine) ProtoMessage()    {}
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{3}
}

func (m *VirtualMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachine.Unmarshal(m, b)
}
func (m *VirtualMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachine.Marshal(b, m, deterministic)
}
func (m *VirtualMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachine.Merge(m, src)
}
func (m *VirtualMachine) XXX_Size() int {
	return xxx_messageInfo_VirtualMachine.Size(m)
}
func (m *VirtualMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachine.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachine proto.InternalMessageInfo

func (m *VirtualMachine) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VirtualMachine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualMachine) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *VirtualMachine) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *VirtualMachine) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *VirtualMachine) GetMemoryMb() uint32 {
	if m != nil {
		return m.MemoryMb
	}
	return 0
}

func (m *VirtualMachine) GetCpuCores() uint32 {
	if m != nil {
		return m.CpuCores
	}
	return 0
}

func (m *VirtualMachine) GetIpv4() *IPConfig {
	if m != nil {
		return m.Ipv4
	}
	return nil
}

func (m *VirtualMachine) GetIpv6() *IPConfig {
	if m != nil {
		return m.Ipv6
	}
	return nil
}

type ProvisionVirtualMachineRequest struct {
	RequestId            string          `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	VirtualMachine       *VirtualMachine `protobuf:"bytes,2,opt,name=virtual_machine,json=virtualMachine,proto3" json:"virtual_machine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProvisionVirtualMachineRequest) Reset()         { *m = ProvisionVirtualMachineRequest{} }
func (m *ProvisionVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionVirtualMachineRequest) ProtoMessage()    {}
func (*ProvisionVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{4}
}

func (m *ProvisionVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionVirtualMachineRequest.Unmarshal(m, b)
}
func (m *ProvisionVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionVirtualMachineRequest.Merge(m, src)
}
func (m *ProvisionVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionVirtualMachineRequest.Size(m)
}
func (m *ProvisionVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionVirtualMachineRequest proto.InternalMessageInfo

func (m *ProvisionVirtualMachineRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ProvisionVirtualMachineRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "proto.Result")
	proto.RegisterType((*ServiceResult)(nil), "proto.ServiceResult")
	proto.RegisterType((*IPConfig)(nil), "proto.IPConfig")
	proto.RegisterType((*VirtualMachine)(nil), "proto.VirtualMachine")
	proto.RegisterType((*ProvisionVirtualMachineRequest)(nil), "proto.ProvisionVirtualMachineRequest")
}

func init() { proto.RegisterFile("provisionize.proto", fileDescriptor_551987ef9813264c) }

var fileDescriptor_551987ef9813264c = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcb, 0x8b, 0xd3, 0x40,
	0x18, 0xb7, 0xd9, 0x6e, 0xb7, 0xf9, 0xda, 0x74, 0x61, 0x54, 0x08, 0x8a, 0x52, 0x53, 0x84, 0x9e,
	0xf6, 0x50, 0x65, 0x4f, 0xe2, 0x65, 0x41, 0x58, 0xb0, 0x52, 0x46, 0xf0, 0x26, 0x21, 0x9d, 0x7c,
	0xcd, 0x0e, 0xe4, 0xb5, 0x33, 0x93, 0xe8, 0xae, 0x07, 0xff, 0x09, 0xff, 0x60, 0xc9, 0x3c, 0x96,
	0xa4, 0xa0, 0xec, 0xa9, 0xf3, 0x7b, 0x7c, 0xcf, 0x7e, 0x01, 0x52, 0x8b, 0xaa, 0xe5, 0x92, 0x57,
	0x25, 0xbf, 0xc7, 0x8b, 0x5a, 0x54, 0xaa, 0x22, 0xa7, 0xfa, 0x27, 0xba, 0x87, 0x09, 0x45, 0xd9,
	0xe4, 0x8a, 0x84, 0x70, 0x26, 0x1b, 0xc6, 0x50, 0xca, 0x70, 0xb4, 0x1c, 0xad, 0xa7, 0xd4, 0xc1,
	0x4e, 0x29, 0x50, 0xca, 0x24, 0xc3, 0xf0, 0x64, 0x39, 0x5a, 0xfb, 0xd4, 0x41, 0xf2, 0x01, 0x16,
	0x12, 0x45, 0xcb, 0x19, 0x9a, 0x24, 0x32, 0xf4, 0x96, 0x27, 0xeb, 0xd9, 0xe6, 0x99, 0x29, 0x72,
	0xf1, 0xb5, 0x2f, 0xd2, 0x23, 0x6f, 0xf4, 0x0b, 0x82, 0x81, 0x81, 0x10, 0x18, 0x97, 0x49, 0x81,
	0xba, 0xbe, 0x4f, 0xf5, 0xbb, 0xdf, 0x96, 0xf7, 0xd8, 0xb6, 0x22, 0x98, 0xa7, 0xb8, 0x6f, 0xb2,
	0xad, 0x95, 0xc7, 0x5a, 0x1e, 0x70, 0x11, 0x83, 0xe9, 0xf5, 0xee, 0xaa, 0x2a, 0x0f, 0x3c, 0xeb,
	0x32, 0x25, 0x69, 0x2a, 0xdc, 0xe8, 0x3e, 0x75, 0x90, 0xac, 0x20, 0xa8, 0x05, 0x1e, 0xf8, 0xcf,
	0x38, 0xc7, 0x32, 0x53, 0x37, 0xba, 0x87, 0x80, 0xce, 0x0d, 0xf9, 0x59, 0x73, 0x5d, 0x78, 0x96,
	0x28, 0xfc, 0x91, 0xdc, 0xb9, 0x46, 0x2c, 0x8c, 0xfe, 0x78, 0xb0, 0xf8, 0xc6, 0x85, 0x6a, 0x92,
	0x7c, 0x9b, 0xb0, 0x1b, 0x5e, 0x22, 0x59, 0x80, 0xc7, 0x53, 0x5b, 0xc6, 0xe3, 0xe9, 0xc3, 0xcc,
	0x5e, 0x6f, 0x66, 0x02, 0xe3, 0xc3, 0x6d, 0x5a, 0xda, 0x6c, 0xfa, 0x4d, 0xde, 0xc0, 0x9c, 0xe5,
	0x8d, 0x54, 0x28, 0x62, 0xed, 0x37, 0x33, 0xcd, 0x2c, 0xf7, 0xa5, 0x0b, 0x5b, 0x41, 0xa0, 0xb0,
	0xa8, 0xf3, 0x44, 0xa1, 0xf1, 0x9c, 0x9a, 0xb9, 0x1d, 0xa9, 0x4d, 0x2f, 0xc1, 0x2f, 0xb0, 0xa8,
	0xc4, 0x5d, 0x5c, 0xec, 0xc3, 0x89, 0x9e, 0x66, 0x6a, 0x88, 0xed, 0xbe, 0x13, 0x59, 0xdd, 0xc4,
	0xac, 0x12, 0x28, 0xc3, 0x33, 0x23, 0xb2, 0xba, 0xb9, 0xea, 0x30, 0x59, 0xc1, 0x98, 0xd7, 0xed,
	0xfb, 0x70, 0xba, 0x1c, 0xad, 0x67, 0x9b, 0x73, 0xfb, 0x17, 0xbb, 0x25, 0x52, 0x2d, 0x5a, 0xd3,
	0x65, 0xe8, 0xff, 0xdb, 0x74, 0x19, 0xfd, 0x86, 0xd7, 0x3b, 0x77, 0x91, 0xc3, 0xf5, 0x50, 0xbc,
	0x6d, 0x50, 0x2a, 0xf2, 0x0a, 0x40, 0x98, 0x67, 0xfc, 0xb0, 0x2d, 0xdf, 0x32, 0xd7, 0x29, 0xf9,
	0x08, 0xe7, 0xad, 0x89, 0x8b, 0x0b, 0x13, 0xa8, 0xf7, 0x37, 0xdb, 0x3c, 0xb7, 0x05, 0x8f, 0xb2,
	0x2e, 0xda, 0x01, 0xde, 0x7c, 0x87, 0xa7, 0xbb, 0xde, 0x27, 0x61, 0xaf, 0x90, 0x7c, 0x82, 0x79,
	0x9f, 0x26, 0x6f, 0x6d, 0xb6, 0xff, 0x37, 0xfb, 0x22, 0xb0, 0x36, 0x73, 0xc5, 0xd1, 0x93, 0xfd,
	0x44, 0xe3, 0x77, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x67, 0x08, 0x29, 0x78, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProvisionizeServiceClient is the client API for ProvisionizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProvisionizeServiceClient interface {
	Provisionize(ctx context.Context, in *ProvisionVirtualMachineRequest, opts ...grpc.CallOption) (*Result, error)
}

type provisionizeServiceClient struct {
	cc *grpc.ClientConn
}

func NewProvisionizeServiceClient(cc *grpc.ClientConn) ProvisionizeServiceClient {
	return &provisionizeServiceClient{cc}
}

func (c *provisionizeServiceClient) Provisionize(ctx context.Context, in *ProvisionVirtualMachineRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/proto.ProvisionizeService/Provisionize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionizeServiceServer is the server API for ProvisionizeService service.
type ProvisionizeServiceServer interface {
	Provisionize(context.Context, *ProvisionVirtualMachineRequest) (*Result, error)
}

func RegisterProvisionizeServiceServer(s *grpc.Server, srv ProvisionizeServiceServer) {
	s.RegisterService(&_ProvisionizeService_serviceDesc, srv)
}

func _ProvisionizeService_Provisionize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionizeServiceServer).Provisionize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProvisionizeService/Provisionize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionizeServiceServer).Provisionize(ctx, req.(*ProvisionVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProvisionizeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProvisionizeService",
	HandlerType: (*ProvisionizeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Provisionize",
			Handler:    _ProvisionizeService_Provisionize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provisionize.proto",
}
