// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provisionize.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusUpdate struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebugMessage         string   `protobuf:"bytes,3,opt,name=debugMessage,proto3" json:"debugMessage,omitempty"`
	Failed               bool     `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusUpdate) Reset()         { *m = StatusUpdate{} }
func (m *StatusUpdate) String() string { return proto.CompactTextString(m) }
func (*StatusUpdate) ProtoMessage()    {}
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{0}
}

func (m *StatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusUpdate.Unmarshal(m, b)
}
func (m *StatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusUpdate.Marshal(b, m, deterministic)
}
func (m *StatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusUpdate.Merge(m, src)
}
func (m *StatusUpdate) XXX_Size() int {
	return xxx_messageInfo_StatusUpdate.Size(m)
}
func (m *StatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_StatusUpdate proto.InternalMessageInfo

func (m *StatusUpdate) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *StatusUpdate) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StatusUpdate) GetDebugMessage() string {
	if m != nil {
		return m.DebugMessage
	}
	return ""
}

func (m *StatusUpdate) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

type IPConfig struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength         uint32   `protobuf:"varint,2,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	Gateway              string   `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPConfig) Reset()         { *m = IPConfig{} }
func (m *IPConfig) String() string { return proto.CompactTextString(m) }
func (*IPConfig) ProtoMessage()    {}
func (*IPConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{1}
}

func (m *IPConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPConfig.Unmarshal(m, b)
}
func (m *IPConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPConfig.Marshal(b, m, deterministic)
}
func (m *IPConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPConfig.Merge(m, src)
}
func (m *IPConfig) XXX_Size() int {
	return xxx_messageInfo_IPConfig.Size(m)
}
func (m *IPConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IPConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IPConfig proto.InternalMessageInfo

func (m *IPConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *IPConfig) GetPrefixLength() uint32 {
	if m != nil {
		return m.PrefixLength
	}
	return 0
}

func (m *IPConfig) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

type VirtualMachine struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Template             string    `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Fqdn                 string    `protobuf:"bytes,4,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	ClusterName          string    `protobuf:"bytes,5,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	MemoryMb             uint32    `protobuf:"varint,6,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuCores             uint32    `protobuf:"varint,7,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	Ipv4                 *IPConfig `protobuf:"bytes,8,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6                 *IPConfig `protobuf:"bytes,9,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VirtualMachine) Reset()         { *m = VirtualMachine{} }
func (m *VirtualMachine) String() string { return proto.CompactTextString(m) }
func (*VirtualMachine) ProtoMessage()    {}
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{2}
}

func (m *VirtualMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachine.Unmarshal(m, b)
}
func (m *VirtualMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachine.Marshal(b, m, deterministic)
}
func (m *VirtualMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachine.Merge(m, src)
}
func (m *VirtualMachine) XXX_Size() int {
	return xxx_messageInfo_VirtualMachine.Size(m)
}
func (m *VirtualMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachine.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachine proto.InternalMessageInfo

func (m *VirtualMachine) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VirtualMachine) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *VirtualMachine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualMachine) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *VirtualMachine) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *VirtualMachine) GetMemoryMb() uint32 {
	if m != nil {
		return m.MemoryMb
	}
	return 0
}

func (m *VirtualMachine) GetCpuCores() uint32 {
	if m != nil {
		return m.CpuCores
	}
	return 0
}

func (m *VirtualMachine) GetIpv4() *IPConfig {
	if m != nil {
		return m.Ipv4
	}
	return nil
}

func (m *VirtualMachine) GetIpv6() *IPConfig {
	if m != nil {
		return m.Ipv6
	}
	return nil
}

type ProvisionizeRequest struct {
	RequestId            string          `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	VirtualMachine       *VirtualMachine `protobuf:"bytes,2,opt,name=virtual_machine,json=virtualMachine,proto3" json:"virtual_machine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProvisionizeRequest) Reset()         { *m = ProvisionizeRequest{} }
func (m *ProvisionizeRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionizeRequest) ProtoMessage()    {}
func (*ProvisionizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_551987ef9813264c, []int{3}
}

func (m *ProvisionizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionizeRequest.Unmarshal(m, b)
}
func (m *ProvisionizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionizeRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionizeRequest.Merge(m, src)
}
func (m *ProvisionizeRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionizeRequest.Size(m)
}
func (m *ProvisionizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionizeRequest proto.InternalMessageInfo

func (m *ProvisionizeRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ProvisionizeRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusUpdate)(nil), "proto.StatusUpdate")
	proto.RegisterType((*IPConfig)(nil), "proto.IPConfig")
	proto.RegisterType((*VirtualMachine)(nil), "proto.VirtualMachine")
	proto.RegisterType((*ProvisionizeRequest)(nil), "proto.ProvisionizeRequest")
}

func init() { proto.RegisterFile("provisionize.proto", fileDescriptor_551987ef9813264c) }

var fileDescriptor_551987ef9813264c = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0x48, 0x53, 0x7b, 0xe2, 0xa6, 0xd2, 0x54, 0x20, 0x2b, 0x08, 0x29, 0xb8, 0x97,
	0x9c, 0x2a, 0x14, 0x50, 0x8f, 0x5c, 0x02, 0x87, 0x4a, 0x04, 0x55, 0xae, 0xe0, 0x6a, 0x6d, 0xec,
	0x89, 0xbb, 0x92, 0xff, 0x6c, 0x77, 0xd7, 0x86, 0xf2, 0x02, 0x1c, 0x78, 0x0a, 0xde, 0x14, 0x79,
	0x77, 0x1d, 0x25, 0x12, 0x9c, 0x7a, 0xca, 0x7e, 0xdf, 0xb7, 0xd9, 0x99, 0xf9, 0x79, 0x00, 0x85,
	0x6c, 0x3a, 0xae, 0x78, 0x53, 0xf3, 0x9f, 0x74, 0x25, 0x64, 0xa3, 0x1b, 0x3c, 0x31, 0x3f, 0xf1,
	0x2f, 0x0f, 0xc2, 0x3b, 0xcd, 0x74, 0xab, 0xbe, 0x8a, 0x9c, 0x69, 0xc2, 0x37, 0x10, 0x2a, 0x92,
	0x1d, 0xcf, 0x28, 0xad, 0x59, 0x45, 0x91, 0xb7, 0xf0, 0x96, 0x41, 0x32, 0x75, 0xde, 0x17, 0x56,
	0x11, 0x46, 0x70, 0x5a, 0x91, 0x52, 0xac, 0xa0, 0x68, 0x64, 0xd2, 0x41, 0x62, 0x0c, 0x61, 0x4e,
	0xdb, 0xb6, 0xd8, 0xb8, 0xf8, 0xb9, 0x89, 0x8f, 0x3c, 0x7c, 0x09, 0x93, 0x1d, 0xe3, 0x25, 0xe5,
	0xd1, 0x78, 0xe1, 0x2d, 0xfd, 0xc4, 0xa9, 0x38, 0x03, 0xff, 0xe6, 0x76, 0xdd, 0xd4, 0x3b, 0x5e,
	0xf4, 0x15, 0x58, 0x9e, 0x4b, 0x52, 0xca, 0xd5, 0x1f, 0x24, 0x5e, 0xc2, 0x99, 0x90, 0xb4, 0xe3,
	0x3f, 0xd2, 0x92, 0xea, 0x42, 0xdf, 0x9b, 0x0e, 0xce, 0x92, 0xd0, 0x9a, 0x9f, 0x8d, 0xd7, 0xff,
	0xbd, 0x60, 0x9a, 0xbe, 0xb3, 0x47, 0xd7, 0xc1, 0x20, 0xe3, 0xdf, 0x23, 0x98, 0x7d, 0xe3, 0x52,
	0xb7, 0xac, 0xdc, 0xb0, 0xec, 0x9e, 0xd7, 0x84, 0x33, 0x18, 0xf1, 0xdc, 0x95, 0x19, 0xf1, 0x1c,
	0xe7, 0xe0, 0x6b, 0xaa, 0x44, 0xc9, 0xf4, 0x30, 0xde, 0x5e, 0x23, 0xc2, 0xd8, 0x40, 0xb1, 0xaf,
	0x9a, 0x73, 0xef, 0xed, 0x1e, 0xf2, 0xda, 0x4c, 0x13, 0x24, 0xe6, 0xdc, 0x43, 0xcc, 0xca, 0x56,
	0x69, 0x92, 0x16, 0xe2, 0x89, 0x85, 0xe8, 0x3c, 0x03, 0xf1, 0x15, 0x04, 0x15, 0x55, 0x8d, 0x7c,
	0x4c, 0xab, 0x6d, 0x34, 0x31, 0x43, 0xf8, 0xd6, 0xd8, 0x6c, 0xfb, 0x30, 0x13, 0x6d, 0x9a, 0x35,
	0x92, 0x54, 0x74, 0x6a, 0xc3, 0x4c, 0xb4, 0xeb, 0x5e, 0xe3, 0x25, 0x8c, 0xb9, 0xe8, 0xde, 0x47,
	0xfe, 0xc2, 0x5b, 0x4e, 0x57, 0xe7, 0xf6, 0x7b, 0x5e, 0x0d, 0xec, 0x12, 0x13, 0xba, 0x4b, 0xd7,
	0x51, 0xf0, 0xff, 0x4b, 0xd7, 0xb1, 0x86, 0x8b, 0xdb, 0x83, 0xcd, 0x48, 0xe8, 0xa1, 0x25, 0xa5,
	0xf1, 0x35, 0x80, 0xb4, 0xc7, 0x74, 0x4f, 0x26, 0x70, 0xce, 0x4d, 0x8e, 0x1f, 0xe0, 0xbc, 0xb3,
	0x08, 0xd3, 0xca, 0x32, 0x34, 0x9c, 0xa6, 0xab, 0x17, 0xae, 0xca, 0x31, 0xe0, 0x64, 0xd6, 0x1d,
	0xe9, 0xd5, 0x1f, 0xef, 0xb8, 0xec, 0x9d, 0x5d, 0x2d, 0x5c, 0x43, 0x78, 0x68, 0xe3, 0xdc, 0x3d,
	0xf7, 0x8f, 0x16, 0xe7, 0x17, 0x2e, 0x3b, 0x5c, 0xdd, 0xf8, 0xd9, 0x5b, 0x0f, 0x3f, 0xc1, 0xec,
	0x23, 0x89, 0xa7, 0x3e, 0xb3, 0x9d, 0x18, 0xff, 0xdd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e,
	0xb8, 0x80, 0x65, 0x3a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProvisionizeServiceClient is the client API for ProvisionizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProvisionizeServiceClient interface {
	Provisionize(ctx context.Context, in *ProvisionizeRequest, opts ...grpc.CallOption) (ProvisionizeService_ProvisionizeClient, error)
	Deprovisionize(ctx context.Context, in *ProvisionizeRequest, opts ...grpc.CallOption) (ProvisionizeService_DeprovisionizeClient, error)
}

type provisionizeServiceClient struct {
	cc *grpc.ClientConn
}

func NewProvisionizeServiceClient(cc *grpc.ClientConn) ProvisionizeServiceClient {
	return &provisionizeServiceClient{cc}
}

func (c *provisionizeServiceClient) Provisionize(ctx context.Context, in *ProvisionizeRequest, opts ...grpc.CallOption) (ProvisionizeService_ProvisionizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProvisionizeService_serviceDesc.Streams[0], "/proto.ProvisionizeService/Provisionize", opts...)
	if err != nil {
		return nil, err
	}
	x := &provisionizeServiceProvisionizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProvisionizeService_ProvisionizeClient interface {
	Recv() (*StatusUpdate, error)
	grpc.ClientStream
}

type provisionizeServiceProvisionizeClient struct {
	grpc.ClientStream
}

func (x *provisionizeServiceProvisionizeClient) Recv() (*StatusUpdate, error) {
	m := new(StatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *provisionizeServiceClient) Deprovisionize(ctx context.Context, in *ProvisionizeRequest, opts ...grpc.CallOption) (ProvisionizeService_DeprovisionizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProvisionizeService_serviceDesc.Streams[1], "/proto.ProvisionizeService/Deprovisionize", opts...)
	if err != nil {
		return nil, err
	}
	x := &provisionizeServiceDeprovisionizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProvisionizeService_DeprovisionizeClient interface {
	Recv() (*StatusUpdate, error)
	grpc.ClientStream
}

type provisionizeServiceDeprovisionizeClient struct {
	grpc.ClientStream
}

func (x *provisionizeServiceDeprovisionizeClient) Recv() (*StatusUpdate, error) {
	m := new(StatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProvisionizeServiceServer is the server API for ProvisionizeService service.
type ProvisionizeServiceServer interface {
	Provisionize(*ProvisionizeRequest, ProvisionizeService_ProvisionizeServer) error
	Deprovisionize(*ProvisionizeRequest, ProvisionizeService_DeprovisionizeServer) error
}

// UnimplementedProvisionizeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProvisionizeServiceServer struct {
}

func (*UnimplementedProvisionizeServiceServer) Provisionize(req *ProvisionizeRequest, srv ProvisionizeService_ProvisionizeServer) error {
	return status.Errorf(codes.Unimplemented, "method Provisionize not implemented")
}
func (*UnimplementedProvisionizeServiceServer) Deprovisionize(req *ProvisionizeRequest, srv ProvisionizeService_DeprovisionizeServer) error {
	return status.Errorf(codes.Unimplemented, "method Deprovisionize not implemented")
}

func RegisterProvisionizeServiceServer(s *grpc.Server, srv ProvisionizeServiceServer) {
	s.RegisterService(&_ProvisionizeService_serviceDesc, srv)
}

func _ProvisionizeService_Provisionize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProvisionizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProvisionizeServiceServer).Provisionize(m, &provisionizeServiceProvisionizeServer{stream})
}

type ProvisionizeService_ProvisionizeServer interface {
	Send(*StatusUpdate) error
	grpc.ServerStream
}

type provisionizeServiceProvisionizeServer struct {
	grpc.ServerStream
}

func (x *provisionizeServiceProvisionizeServer) Send(m *StatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _ProvisionizeService_Deprovisionize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProvisionizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProvisionizeServiceServer).Deprovisionize(m, &provisionizeServiceDeprovisionizeServer{stream})
}

type ProvisionizeService_DeprovisionizeServer interface {
	Send(*StatusUpdate) error
	grpc.ServerStream
}

type provisionizeServiceDeprovisionizeServer struct {
	grpc.ServerStream
}

func (x *provisionizeServiceDeprovisionizeServer) Send(m *StatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

var _ProvisionizeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProvisionizeService",
	HandlerType: (*ProvisionizeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Provisionize",
			Handler:       _ProvisionizeService_Provisionize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Deprovisionize",
			Handler:       _ProvisionizeService_Deprovisionize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "provisionize.proto",
}
